# Generated by Django 2.2 on 2020-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20, unique=True, verbose_name='评论id')),
                ('uid', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('avatar', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像')),
                ('sentiments', models.FloatField(blank=True, null=True, verbose_name='情感分析')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-pub_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20, unique=True, verbose_name='产品id')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='价格')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='分类')),
                ('category_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='category')),
                ('price_from', models.CharField(blank=True, max_length=20, null=True, verbose_name='产品来源')),
                ('img', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品图片')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
                'ordering': ['-pub_date'],
                'managed': False,
            },
        ),
    ]
