# Generated by Django 2.2 on 2020-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('user_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='用户名')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='电影id')),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='imdb_id')),
                ('movie_name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('release_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='上映日期')),
                ('movie_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='电影类型')),
                ('runtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='电影时长')),
                ('area', models.CharField(blank=True, max_length=20, null=True, verbose_name='区域')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='语言')),
                ('img_src', models.CharField(blank=True, max_length=255, null=True, verbose_name='海报')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('rate_count', models.IntegerField(blank=True, null=True, verbose_name='评价人数')),
                ('indent', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面链接')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'movies',
                'ordering': ['-rate'],
                'managed': False,
            },
        ),
    ]
